image:
  file: .gitpod.dockerfile
ports:
  - port: 8787
    onOpen: open-preview
tasks:
  - command: /usr/lib/rstudio-server/bin/rstudio-server start
  - command: Rscript clone.R
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
